# https://kubernetes.io/docs/concepts/services-networking/ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deepwiki-ingress
  namespace: {{ .Values.spec.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-forward: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.spec.ingress.webUrl }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: deepwiki-service
            port:
              name: web
  - host: {{ .Values.spec.ingress.apiUrl }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: deepwiki-service
            port:
              name: api
