# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: deepwiki-service
  namespace: {{ .Values.spec.namespace }}
spec:
  selector:
    app: deepwiki-app
  ports:
  - name: web
    port: 3000
  - name: api
    port: 8001
